name: Docker Build & Security Scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t docker-optim-demo .

    - name: Scan for vulnerabilities
      run: |
        docker scan --file Dockerfile --exclude-base docker-optim-demo
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: |
        docker tag docker-optim-demo ${{ secrets.DOCKER_USERNAME }}/optimized-flask:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/optimized-flask:latest