name: Docker Build & Security Scan

on:
  push:
    paths:
      - 'docker-optimization-project/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      working-directory: ./docker-optimization-project
      run: docker build -t docker-optim-demo .

    - name: Scan for vulnerabilities
      working-directory: ./docker-optimization-project
      run: |
        echo "Starting basic vulnerability scan..."
        docker scan docker-optim-demo || echo "Scan completed (vulnerabilities may exist)"
        echo "For detailed results, consider using Snyk CLI directly"
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      working-directory: ./docker-optimization-project
      run: |
        docker tag docker-optim-demo ${{ secrets.DOCKER_USERNAME }}/optimized-flask:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/optimized-flask:latest